version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - my_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://user:password@postgres/database
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8000
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    networks:
      - my_network

networks:
  my_network: 
 
volumes:
  postgres_data: